language: generic

services:
  - docker

jobs:
  include:
    - stage: test and build in docker
      script: if .travis/has-changed.sh $TRAVIS_COMMIT_RANGE projects/portal; then docker build -t portal projects/portal; fi
    - stage: deploy
      script: docker images # This is a test command for now
      if: branch = master AND tag IS present
