language: generic

env:
  global:
    - BEANSTALK_ZIP_FILENAME=dockerrun.zip

before_deploy:
- ./.travis/create-dockerrun-file.sh

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-1
  app: cop-watch-app
  env: cop-watch-production-environment
  bucket_name: cop-watch-production-bucket
  zip_file: $BEANSTALK_ZIP_FILENAME
  on:
    tags: true